symfonyuk-php:
  extends:
    file: ./docker/php/php.yml
    service: php-fpm
  volumes:
    - ./:/symfony.org.uk
  working_dir: /symfony.org.uk
  hostname: symfony.org.uk
  container_name: symfonyuk-php
symfonyuk-slackin:
  image: chk1/slackin
  environment:
    SLACK_TOKEN: ''
    SLACK_ORG: symfony-uk
  ports:
    - "3000:3000"
  container_name: symfonyuk-slackin
symfonyuk-nginx:
  image: nginx:latest
  links:
    - symfonyuk-php
    - symfonyuk-slackin
  volumes_from:
    - symfonyuk-php
  volumes:
    - ./docker/nginx/:/etc/nginx/conf.d/
  ports:
    - "80:80"
  container_name: symfonyuk-nginx
